name: gosnack_client
description: "Aplicativo do cliente GoSnack, permitindo que alunos, professores e visitantes visualizem o cardápio das lanchonetes do colégio, façam pedidos e acompanhem atualizações para retirada."

publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.9.2

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter

# Dependências de desenvolvimento
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Pacotes do Flutter
flutter:
  uses-material-design: true

  # Local assets
  assets:
    - assets/logos/ # Logos do aplicativo

  # Local Fonts
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
